name: rust

on:
  push:
    branches:
      - '*'

jobs:
  rsanim:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - run: cargo clippy --all
      - run: cargo build
      - run: cargo test
